name: CrypticRPG
main: me.neildennis.crypticrpg.Cryptic
version: 1.0
depend: [WorldGuard,WorldEdit]
commands:
  item:
    usage: /<command>
  spawner:
    usage: /<command>
  ban:
    usage: /<command> <user> <reason>
  zone:
    usage: /<command>
  setrank:
    usage: /<command>